sudo: false
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g codecov
script:
  - npm run test:bs
after_success:
  - codecov
after_failure:
  - codecov
env:
  global:
    - secure: YVMBKSjPWE7VeztBBBtGs64OtmfyDi9LHcHOYwmIJDj4lT9fldfdAFNIOsTkW2C+8QgGjYXUcz8QgbyLhFbLCE9o70C22O2bn9kLrc5SQ7mcI8NJpimcIOcPLapMfppJZBcBVX1ngWA6XZei9UaCC8SrkZcbHmlR1aQdFTfG7YGHW7YIGoEQj0eKythNCjr+xrkL2HNfSqatDZM3qyw9pWYuZfkd3CVkIJ5ArURSE2508NPn2qaN2SQEAwrLnUzYgCz9BQhh3hgl1lm//s24KJLowNKrtct9nw0ZEHmdIZM1EsTihYdSCQ+CreMu+NdHQr6e6VOMa7EvqecGwwase45yfnjdrLRD4VrPfX3HdqEniRxQ6MLDZJMbm5RMvuCMRj1MmGpwdFrG/H2VrbIPOH6PVj9ydB8dK1uOFtDFhPoJNEpYYvneqVyWO+8RTdwunV/aB1XaEqMAMPKfH7B9fMIC7BMOE4K3zgN3eBdAN9KQP5k1y9TrgaIQhTmQMSIyL+FNePKVupESlJcI/d4QFSoRSvpUEo8yL0XtJ8k76bsGy57m63rb+0Gc/nbK7pESjbEzIFiS1tpcoOuJ/IIRQ1b9ziMYpbXeKCi05I9aYCmQXXS/HwpsdAKMf5dBk9GaDD8ZZahGq+7j6mdurYMpYxixa7SZ9OisIxOsD0vgiZY=
    - secure: eCbsreGxuyArGxrnN6MsfTQJb71/lUIou00QIdLkKvEGJFoD0hizBqX+9zL5pOv5hn9GacQwuA4H9N5YjmJ+RA9G37mtJXViPSId7yqso8HhrpLRbxkVQ1AzJw6YDFjV6iL+cNFpSKRsRLYpu+S9TuwzIdhnm+ZXAdKRY4/T4Pkev7EM/Ybfi2SGtRIhFwrpMb80JloJKa7EgnhNKqALFwRnSRBwm+AMQrFSHnaafQzkp/GozZ2V1mquFJ9CSZJwuZHSDixbpQjs6jHO77K5u+CLWJkKFG98i10tyl6BSnlNK/QgLVf9UIgYQPmKaoI4VEP9oSPEqngu8V3DjBumJXvaIZcnMjeX3zyA4Mmd5NlvWjHGAcD4MgJnxWFCeP7sGMwP2j1byaZ4HPqGef5hfxaDomLimdwymaJKwNGSKFpNtMiIwpZEKQoxxddZvTGcv58vHDH8DVae9q8mpVzUuueRyTosr4cVBOx6KG0045tKaUgB9ddLFsVAW9/7trv2cFbGYgNBJnK0yOlEWZTmIlEhh0+N7uqmzT+Y44Nt7LgZNwwt6OgsvG/ovb0Y+j/sEUtAjLUIvI3oDm9y+fTcZ/TycXIwHHit1nnKi4suZEULwJEIZPCJtsNHQo+tsefq05jEV6eveIK7q7hR4hVXtjthMNJ35J3BccpEK43Tqho=
